//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4927.
// 
#pragma warning disable 1591

namespace fint.Forms.serverFINTFachada {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="serverFINTFachadaSoap", Namespace="http://tempuri.org/")]
    public partial class serverFINTFachada : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback agregarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback chequearUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback modificarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerProveedoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback ingresarCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerUsuariosXTipoOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerCuentaXusuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ingresarGastoOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerCuentasXusuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerGastosXusuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback realizarPagoOperationCompleted;
        
        private System.Threading.SendOrPostCallback realizarDepositoOperationCompleted;
        
        private System.Threading.SendOrPostCallback realizarExtraccionOperationCompleted;
        
        private System.Threading.SendOrPostCallback realizarTransferenciaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public serverFINTFachada() {
            this.Url = global::fint.Forms.Properties.Settings.Default.FINTDesktop_serverFINTFachada_serverFINTFachada;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event agregarUsuarioCompletedEventHandler agregarUsuarioCompleted;
        
        /// <remarks/>
        public event chequearUsuarioCompletedEventHandler chequearUsuarioCompleted;
        
        /// <remarks/>
        public event modificarUsuarioCompletedEventHandler modificarUsuarioCompleted;
        
        /// <remarks/>
        public event obtenerProveedoresCompletedEventHandler obtenerProveedoresCompleted;
        
        /// <remarks/>
        public event ingresarCuentaCompletedEventHandler ingresarCuentaCompleted;
        
        /// <remarks/>
        public event obtenerUsuariosXTipoCompletedEventHandler obtenerUsuariosXTipoCompleted;
        
        /// <remarks/>
        public event obtenerCuentaXusuarioCompletedEventHandler obtenerCuentaXusuarioCompleted;
        
        /// <remarks/>
        public event ingresarGastoCompletedEventHandler ingresarGastoCompleted;
        
        /// <remarks/>
        public event obtenerCuentasXusuarioCompletedEventHandler obtenerCuentasXusuarioCompleted;
        
        /// <remarks/>
        public event obtenerGastosXusuarioCompletedEventHandler obtenerGastosXusuarioCompleted;
        
        /// <remarks/>
        public event realizarPagoCompletedEventHandler realizarPagoCompleted;
        
        /// <remarks/>
        public event realizarDepositoCompletedEventHandler realizarDepositoCompleted;
        
        /// <remarks/>
        public event realizarExtraccionCompletedEventHandler realizarExtraccionCompleted;
        
        /// <remarks/>
        public event realizarTransferenciaCompletedEventHandler realizarTransferenciaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/agregarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int agregarUsuario(string nombre, string login, string passwd, rol tipo) {
            object[] results = this.Invoke("agregarUsuario", new object[] {
                        nombre,
                        login,
                        passwd,
                        tipo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void agregarUsuarioAsync(string nombre, string login, string passwd, rol tipo) {
            this.agregarUsuarioAsync(nombre, login, passwd, tipo, null);
        }
        
        /// <remarks/>
        public void agregarUsuarioAsync(string nombre, string login, string passwd, rol tipo, object userState) {
            if ((this.agregarUsuarioOperationCompleted == null)) {
                this.agregarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnagregarUsuarioOperationCompleted);
            }
            this.InvokeAsync("agregarUsuario", new object[] {
                        nombre,
                        login,
                        passwd,
                        tipo}, this.agregarUsuarioOperationCompleted, userState);
        }
        
        private void OnagregarUsuarioOperationCompleted(object arg) {
            if ((this.agregarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.agregarUsuarioCompleted(this, new agregarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/chequearUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet chequearUsuario(string login, string passwd) {
            object[] results = this.Invoke("chequearUsuario", new object[] {
                        login,
                        passwd});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void chequearUsuarioAsync(string login, string passwd) {
            this.chequearUsuarioAsync(login, passwd, null);
        }
        
        /// <remarks/>
        public void chequearUsuarioAsync(string login, string passwd, object userState) {
            if ((this.chequearUsuarioOperationCompleted == null)) {
                this.chequearUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchequearUsuarioOperationCompleted);
            }
            this.InvokeAsync("chequearUsuario", new object[] {
                        login,
                        passwd}, this.chequearUsuarioOperationCompleted, userState);
        }
        
        private void OnchequearUsuarioOperationCompleted(object arg) {
            if ((this.chequearUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.chequearUsuarioCompleted(this, new chequearUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/modificarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool modificarUsuario(string nombre, string passwd, int id) {
            object[] results = this.Invoke("modificarUsuario", new object[] {
                        nombre,
                        passwd,
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void modificarUsuarioAsync(string nombre, string passwd, int id) {
            this.modificarUsuarioAsync(nombre, passwd, id, null);
        }
        
        /// <remarks/>
        public void modificarUsuarioAsync(string nombre, string passwd, int id, object userState) {
            if ((this.modificarUsuarioOperationCompleted == null)) {
                this.modificarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodificarUsuarioOperationCompleted);
            }
            this.InvokeAsync("modificarUsuario", new object[] {
                        nombre,
                        passwd,
                        id}, this.modificarUsuarioOperationCompleted, userState);
        }
        
        private void OnmodificarUsuarioOperationCompleted(object arg) {
            if ((this.modificarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.modificarUsuarioCompleted(this, new modificarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtenerProveedores", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet obtenerProveedores() {
            object[] results = this.Invoke("obtenerProveedores", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerProveedoresAsync() {
            this.obtenerProveedoresAsync(null);
        }
        
        /// <remarks/>
        public void obtenerProveedoresAsync(object userState) {
            if ((this.obtenerProveedoresOperationCompleted == null)) {
                this.obtenerProveedoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerProveedoresOperationCompleted);
            }
            this.InvokeAsync("obtenerProveedores", new object[0], this.obtenerProveedoresOperationCompleted, userState);
        }
        
        private void OnobtenerProveedoresOperationCompleted(object arg) {
            if ((this.obtenerProveedoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerProveedoresCompleted(this, new obtenerProveedoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ingresarCuenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ingresarCuenta(string numero, string descripcion, decimal saldo, int idProveedor, int idUsuario) {
            object[] results = this.Invoke("ingresarCuenta", new object[] {
                        numero,
                        descripcion,
                        saldo,
                        idProveedor,
                        idUsuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ingresarCuentaAsync(string numero, string descripcion, decimal saldo, int idProveedor, int idUsuario) {
            this.ingresarCuentaAsync(numero, descripcion, saldo, idProveedor, idUsuario, null);
        }
        
        /// <remarks/>
        public void ingresarCuentaAsync(string numero, string descripcion, decimal saldo, int idProveedor, int idUsuario, object userState) {
            if ((this.ingresarCuentaOperationCompleted == null)) {
                this.ingresarCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OningresarCuentaOperationCompleted);
            }
            this.InvokeAsync("ingresarCuenta", new object[] {
                        numero,
                        descripcion,
                        saldo,
                        idProveedor,
                        idUsuario}, this.ingresarCuentaOperationCompleted, userState);
        }
        
        private void OningresarCuentaOperationCompleted(object arg) {
            if ((this.ingresarCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ingresarCuentaCompleted(this, new ingresarCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtenerUsuariosXTipo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet obtenerUsuariosXTipo(rol tipo) {
            object[] results = this.Invoke("obtenerUsuariosXTipo", new object[] {
                        tipo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerUsuariosXTipoAsync(rol tipo) {
            this.obtenerUsuariosXTipoAsync(tipo, null);
        }
        
        /// <remarks/>
        public void obtenerUsuariosXTipoAsync(rol tipo, object userState) {
            if ((this.obtenerUsuariosXTipoOperationCompleted == null)) {
                this.obtenerUsuariosXTipoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerUsuariosXTipoOperationCompleted);
            }
            this.InvokeAsync("obtenerUsuariosXTipo", new object[] {
                        tipo}, this.obtenerUsuariosXTipoOperationCompleted, userState);
        }
        
        private void OnobtenerUsuariosXTipoOperationCompleted(object arg) {
            if ((this.obtenerUsuariosXTipoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerUsuariosXTipoCompleted(this, new obtenerUsuariosXTipoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtenerCuentaXusuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet obtenerCuentaXusuario(int idUsuario) {
            object[] results = this.Invoke("obtenerCuentaXusuario", new object[] {
                        idUsuario});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerCuentaXusuarioAsync(int idUsuario) {
            this.obtenerCuentaXusuarioAsync(idUsuario, null);
        }
        
        /// <remarks/>
        public void obtenerCuentaXusuarioAsync(int idUsuario, object userState) {
            if ((this.obtenerCuentaXusuarioOperationCompleted == null)) {
                this.obtenerCuentaXusuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerCuentaXusuarioOperationCompleted);
            }
            this.InvokeAsync("obtenerCuentaXusuario", new object[] {
                        idUsuario}, this.obtenerCuentaXusuarioOperationCompleted, userState);
        }
        
        private void OnobtenerCuentaXusuarioOperationCompleted(object arg) {
            if ((this.obtenerCuentaXusuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerCuentaXusuarioCompleted(this, new obtenerCuentaXusuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ingresarGasto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ingresarGasto(string numero, string concepto, decimal monto, string vencimiento, int estado, int idUsuario, int idcuenta) {
            object[] results = this.Invoke("ingresarGasto", new object[] {
                        numero,
                        concepto,
                        monto,
                        vencimiento,
                        estado,
                        idUsuario,
                        idcuenta});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ingresarGastoAsync(string numero, string concepto, decimal monto, string vencimiento, int estado, int idUsuario, int idcuenta) {
            this.ingresarGastoAsync(numero, concepto, monto, vencimiento, estado, idUsuario, idcuenta, null);
        }
        
        /// <remarks/>
        public void ingresarGastoAsync(string numero, string concepto, decimal monto, string vencimiento, int estado, int idUsuario, int idcuenta, object userState) {
            if ((this.ingresarGastoOperationCompleted == null)) {
                this.ingresarGastoOperationCompleted = new System.Threading.SendOrPostCallback(this.OningresarGastoOperationCompleted);
            }
            this.InvokeAsync("ingresarGasto", new object[] {
                        numero,
                        concepto,
                        monto,
                        vencimiento,
                        estado,
                        idUsuario,
                        idcuenta}, this.ingresarGastoOperationCompleted, userState);
        }
        
        private void OningresarGastoOperationCompleted(object arg) {
            if ((this.ingresarGastoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ingresarGastoCompleted(this, new ingresarGastoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtenerCuentasXusuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet obtenerCuentasXusuario(int idUsuario) {
            object[] results = this.Invoke("obtenerCuentasXusuario", new object[] {
                        idUsuario});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerCuentasXusuarioAsync(int idUsuario) {
            this.obtenerCuentasXusuarioAsync(idUsuario, null);
        }
        
        /// <remarks/>
        public void obtenerCuentasXusuarioAsync(int idUsuario, object userState) {
            if ((this.obtenerCuentasXusuarioOperationCompleted == null)) {
                this.obtenerCuentasXusuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerCuentasXusuarioOperationCompleted);
            }
            this.InvokeAsync("obtenerCuentasXusuario", new object[] {
                        idUsuario}, this.obtenerCuentasXusuarioOperationCompleted, userState);
        }
        
        private void OnobtenerCuentasXusuarioOperationCompleted(object arg) {
            if ((this.obtenerCuentasXusuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerCuentasXusuarioCompleted(this, new obtenerCuentasXusuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtenerGastosXusuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet obtenerGastosXusuario(int idUsuario) {
            object[] results = this.Invoke("obtenerGastosXusuario", new object[] {
                        idUsuario});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerGastosXusuarioAsync(int idUsuario) {
            this.obtenerGastosXusuarioAsync(idUsuario, null);
        }
        
        /// <remarks/>
        public void obtenerGastosXusuarioAsync(int idUsuario, object userState) {
            if ((this.obtenerGastosXusuarioOperationCompleted == null)) {
                this.obtenerGastosXusuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerGastosXusuarioOperationCompleted);
            }
            this.InvokeAsync("obtenerGastosXusuario", new object[] {
                        idUsuario}, this.obtenerGastosXusuarioOperationCompleted, userState);
        }
        
        private void OnobtenerGastosXusuarioOperationCompleted(object arg) {
            if ((this.obtenerGastosXusuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerGastosXusuarioCompleted(this, new obtenerGastosXusuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/realizarPago", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool realizarPago(int idGasto, int idCuenta) {
            object[] results = this.Invoke("realizarPago", new object[] {
                        idGasto,
                        idCuenta});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void realizarPagoAsync(int idGasto, int idCuenta) {
            this.realizarPagoAsync(idGasto, idCuenta, null);
        }
        
        /// <remarks/>
        public void realizarPagoAsync(int idGasto, int idCuenta, object userState) {
            if ((this.realizarPagoOperationCompleted == null)) {
                this.realizarPagoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrealizarPagoOperationCompleted);
            }
            this.InvokeAsync("realizarPago", new object[] {
                        idGasto,
                        idCuenta}, this.realizarPagoOperationCompleted, userState);
        }
        
        private void OnrealizarPagoOperationCompleted(object arg) {
            if ((this.realizarPagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.realizarPagoCompleted(this, new realizarPagoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/realizarDeposito", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool realizarDeposito(int idCuenta, decimal monto, string concepto) {
            object[] results = this.Invoke("realizarDeposito", new object[] {
                        idCuenta,
                        monto,
                        concepto});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void realizarDepositoAsync(int idCuenta, decimal monto, string concepto) {
            this.realizarDepositoAsync(idCuenta, monto, concepto, null);
        }
        
        /// <remarks/>
        public void realizarDepositoAsync(int idCuenta, decimal monto, string concepto, object userState) {
            if ((this.realizarDepositoOperationCompleted == null)) {
                this.realizarDepositoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrealizarDepositoOperationCompleted);
            }
            this.InvokeAsync("realizarDeposito", new object[] {
                        idCuenta,
                        monto,
                        concepto}, this.realizarDepositoOperationCompleted, userState);
        }
        
        private void OnrealizarDepositoOperationCompleted(object arg) {
            if ((this.realizarDepositoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.realizarDepositoCompleted(this, new realizarDepositoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/realizarExtraccion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool realizarExtraccion(int idCuenta, decimal monto, string concepto) {
            object[] results = this.Invoke("realizarExtraccion", new object[] {
                        idCuenta,
                        monto,
                        concepto});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void realizarExtraccionAsync(int idCuenta, decimal monto, string concepto) {
            this.realizarExtraccionAsync(idCuenta, monto, concepto, null);
        }
        
        /// <remarks/>
        public void realizarExtraccionAsync(int idCuenta, decimal monto, string concepto, object userState) {
            if ((this.realizarExtraccionOperationCompleted == null)) {
                this.realizarExtraccionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrealizarExtraccionOperationCompleted);
            }
            this.InvokeAsync("realizarExtraccion", new object[] {
                        idCuenta,
                        monto,
                        concepto}, this.realizarExtraccionOperationCompleted, userState);
        }
        
        private void OnrealizarExtraccionOperationCompleted(object arg) {
            if ((this.realizarExtraccionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.realizarExtraccionCompleted(this, new realizarExtraccionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/realizarTransferencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool realizarTransferencia(int pCuentaOrig, int pCuentaDestino, decimal monto, string concepto) {
            object[] results = this.Invoke("realizarTransferencia", new object[] {
                        pCuentaOrig,
                        pCuentaDestino,
                        monto,
                        concepto});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void realizarTransferenciaAsync(int pCuentaOrig, int pCuentaDestino, decimal monto, string concepto) {
            this.realizarTransferenciaAsync(pCuentaOrig, pCuentaDestino, monto, concepto, null);
        }
        
        /// <remarks/>
        public void realizarTransferenciaAsync(int pCuentaOrig, int pCuentaDestino, decimal monto, string concepto, object userState) {
            if ((this.realizarTransferenciaOperationCompleted == null)) {
                this.realizarTransferenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrealizarTransferenciaOperationCompleted);
            }
            this.InvokeAsync("realizarTransferencia", new object[] {
                        pCuentaOrig,
                        pCuentaDestino,
                        monto,
                        concepto}, this.realizarTransferenciaOperationCompleted, userState);
        }
        
        private void OnrealizarTransferenciaOperationCompleted(object arg) {
            if ((this.realizarTransferenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.realizarTransferenciaCompleted(this, new realizarTransferenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum rol {
        
        /// <remarks/>
        Administrador,
        
        /// <remarks/>
        Usuario,
        
        /// <remarks/>
        Cliente,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void agregarUsuarioCompletedEventHandler(object sender, agregarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class agregarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal agregarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void chequearUsuarioCompletedEventHandler(object sender, chequearUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class chequearUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal chequearUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void modificarUsuarioCompletedEventHandler(object sender, modificarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class modificarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal modificarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void obtenerProveedoresCompletedEventHandler(object sender, obtenerProveedoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerProveedoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerProveedoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ingresarCuentaCompletedEventHandler(object sender, ingresarCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ingresarCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ingresarCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void obtenerUsuariosXTipoCompletedEventHandler(object sender, obtenerUsuariosXTipoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerUsuariosXTipoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerUsuariosXTipoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void obtenerCuentaXusuarioCompletedEventHandler(object sender, obtenerCuentaXusuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerCuentaXusuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerCuentaXusuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ingresarGastoCompletedEventHandler(object sender, ingresarGastoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ingresarGastoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ingresarGastoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void obtenerCuentasXusuarioCompletedEventHandler(object sender, obtenerCuentasXusuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerCuentasXusuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerCuentasXusuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void obtenerGastosXusuarioCompletedEventHandler(object sender, obtenerGastosXusuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerGastosXusuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerGastosXusuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void realizarPagoCompletedEventHandler(object sender, realizarPagoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class realizarPagoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal realizarPagoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void realizarDepositoCompletedEventHandler(object sender, realizarDepositoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class realizarDepositoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal realizarDepositoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void realizarExtraccionCompletedEventHandler(object sender, realizarExtraccionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class realizarExtraccionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal realizarExtraccionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void realizarTransferenciaCompletedEventHandler(object sender, realizarTransferenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class realizarTransferenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal realizarTransferenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591