//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4927.
// 
#pragma warning disable 1591

namespace serverFINT.appProveedorFachadaProxy {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="appProveedorFachadaSoap", Namespace="http://tempuri.org/")]
    public partial class appProveedorFachada : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback obtenerEstadoCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback realizarPagoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public appProveedorFachada() {
            this.Url = global::serverFINT.Properties.Settings.Default.serverFINT_appProveedorFachadaProxy_appProveedorFachada;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event obtenerEstadoCuentaCompletedEventHandler obtenerEstadoCuentaCompleted;
        
        /// <remarks/>
        public event realizarPagoCompletedEventHandler realizarPagoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtenerEstadoCuenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public estadoCuenta obtenerEstadoCuenta(string numcue) {
            object[] results = this.Invoke("obtenerEstadoCuenta", new object[] {
                        numcue});
            return ((estadoCuenta)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerEstadoCuentaAsync(string numcue) {
            this.obtenerEstadoCuentaAsync(numcue, null);
        }
        
        /// <remarks/>
        public void obtenerEstadoCuentaAsync(string numcue, object userState) {
            if ((this.obtenerEstadoCuentaOperationCompleted == null)) {
                this.obtenerEstadoCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerEstadoCuentaOperationCompleted);
            }
            this.InvokeAsync("obtenerEstadoCuenta", new object[] {
                        numcue}, this.obtenerEstadoCuentaOperationCompleted, userState);
        }
        
        private void OnobtenerEstadoCuentaOperationCompleted(object arg) {
            if ((this.obtenerEstadoCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerEstadoCuentaCompleted(this, new obtenerEstadoCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/realizarPago", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool realizarPago(string numcue, decimal monto) {
            object[] results = this.Invoke("realizarPago", new object[] {
                        numcue,
                        monto});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void realizarPagoAsync(string numcue, decimal monto) {
            this.realizarPagoAsync(numcue, monto, null);
        }
        
        /// <remarks/>
        public void realizarPagoAsync(string numcue, decimal monto, object userState) {
            if ((this.realizarPagoOperationCompleted == null)) {
                this.realizarPagoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrealizarPagoOperationCompleted);
            }
            this.InvokeAsync("realizarPago", new object[] {
                        numcue,
                        monto}, this.realizarPagoOperationCompleted, userState);
        }
        
        private void OnrealizarPagoOperationCompleted(object arg) {
            if ((this.realizarPagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.realizarPagoCompleted(this, new realizarPagoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class estadoCuenta {
        
        private decimal totalField;
        
        private gasto[] colgastoField;
        
        /// <remarks/>
        public decimal Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        public gasto[] Colgasto {
            get {
                return this.colgastoField;
            }
            set {
                this.colgastoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class gasto {
        
        private decimal montoField;
        
        private string fechaCompraField;
        
        private string conceptoField;
        
        private string numFactField;
        
        private int estadoField;
        
        /// <remarks/>
        public decimal Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public string FechaCompra {
            get {
                return this.fechaCompraField;
            }
            set {
                this.fechaCompraField = value;
            }
        }
        
        /// <remarks/>
        public string Concepto {
            get {
                return this.conceptoField;
            }
            set {
                this.conceptoField = value;
            }
        }
        
        /// <remarks/>
        public string NumFact {
            get {
                return this.numFactField;
            }
            set {
                this.numFactField = value;
            }
        }
        
        /// <remarks/>
        public int Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void obtenerEstadoCuentaCompletedEventHandler(object sender, obtenerEstadoCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerEstadoCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerEstadoCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public estadoCuenta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((estadoCuenta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void realizarPagoCompletedEventHandler(object sender, realizarPagoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class realizarPagoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal realizarPagoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591